// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ReactPOC.Models;

public partial class Eventos
{
    [Key]
    public int id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string NombreEvento { get; set; }

    [Column(TypeName = "date")]
    public DateTime FechaDesde { get; set; }

    [Column(TypeName = "date")]
    public DateTime FechaHasta { get; set; }

    public bool habilitado { get; set; }

    public int id_tipoIngreso { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Organizador { get; set; }

    [InverseProperty("id_eventoNavigation")]
    public virtual ICollection<Expositores> Expositores { get; set; } = new List<Expositores>();

    [InverseProperty("id_eventoNavigation")]
    public virtual ICollection<Ingresos> Ingresos { get; set; } = new List<Ingresos>();

    [ForeignKey("id_tipoIngreso")]
    [InverseProperty("Eventos")]
    public virtual TipoIngreso id_tipoIngresoNavigation { get; set; }

    // Propiedad calculada para la cantidad de expositores
    [NotMapped] // Indica a EF Core que ignore esta propiedad en la migración de la base de datos
    public int CantidadExpositores { get; set; }
}