// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.Json.Serialization;
using Microsoft.EntityFrameworkCore;

namespace ReactPOC.Models;

public partial class Expositores
{
    [Key]
    public int id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Apellido { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Nombre { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Empresa { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Email { get; set; }

    public bool habilitado { get; set; }

    public int id_evento { get; set; }

    public int id_tipoIngreso { get; set; }

    [Required]
    [StringLength(10)]
    [Unicode(false)]
    public string DNI { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string Ciudad { get; set; }

    [Column(TypeName = "date")]
    public DateTime FechaNacimiento { get; set; }

    [Required]
    [StringLength(1)]
    [Unicode(false)]
    public string Genero { get; set; }

    [JsonIgnore]
    [InverseProperty("id_expositorNavigation")]
    public virtual ICollection<Ingresos> Ingresos { get; set; } = new List<Ingresos>();

    [ForeignKey("id_evento")]
    [InverseProperty("Expositores")]
    public virtual Eventos id_eventoNavigation { get; set; }

    [ForeignKey("id_tipoIngreso")]
    [InverseProperty("Expositores")]
    public virtual TipoIngreso id_tipoIngresoNavigation { get; set; }
}