// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ReactPOC.Models;

public partial class Ingresos
{
    [Key]
    public int id { get; set; }

    public int id_evento { get; set; }

    public int id_expositor { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime fecha { get; set; }

    public bool valido { get; set; }

    [ForeignKey("id_evento")]
    [InverseProperty("Ingresos")]
    public virtual Eventos id_eventoNavigation { get; set; }

    [ForeignKey("id_expositor")]
    [InverseProperty("Ingresos")]
    public virtual Expositores id_expositorNavigation { get; set; }
}