// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ReactPOC.Models;

public partial class Usuarios
{
    [Key]
    public int id { get; set; }

    [Required]
    [StringLength(80)]
    [Unicode(false)]
    public string Username { get; set; }
    [Required]
    [StringLength(80)]
    [Unicode(false)]
    public string Email { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Password { get; set; }
}